POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test Name",
    "number": "123456"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "12345"
}