POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test345600978",
    "number": "12_11233254"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "12345"
}